# Generated by Django 5.0.6 on 2024-06-17 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restroom_app', '0002_rename_address_restroom_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restroom',
            old_name='long',
            new_name='longitude',
        ),
    ]
