# Generated by Django 5.0.6 on 2024-06-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroom_app', '0003_rename_long_restroom_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restroom',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
