# Generated by Django 5.0.6 on 2024-07-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroom_app', '0004_alter_restroom_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='restroom',
            name='api_restroom_key',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
