version: '3'
services:
  api:
    build: .
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    ports:
      - "8080:80"
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restroom_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
      