version: '3'
services:
  api:
    build: .
    command: sh -c "python manage.py migrate && gunicorn reputable_restrooms.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - api
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restroom_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
