
# Generated by Django 5.0.6 on 2024-07-02 01:05



import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0002_alter_image_restroom_alter_image_user'),
        ('restroom_app', '0005_restroom_api_restroom_key'),

        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(

            model_name="image",
            name="restroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restroom_images",
                to="restroom_app.restroom",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
